version: "3.9"  # optional since v1.27.0
services:
  ck-api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    container_name: ck-express-ts
    command: npm run start:dev
    ports:
      - "8081:3001"
    volumes:
      - ./api:/app/api