version: "3.9"  # optional since v1.27.0
services:
  ck-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ck-express-ts
    command: npm run start
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/api