version: "3.9"  # optional since v1.27.0
services:
  ck-vue:
    build:
      dockerfile: Dockerfile.dev
      context: ./client2
    container_name: ck-vue
    command: npm run serve
    ports:
      - "8082:8080"
    volumes:
      - /app/client/node_modules
      - ./client2:/app/client

  ck-vue-vite:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: ck-vue-vite
    command: npm run dev
    ports:
      - "8081:8080"
    volumes:
      - /app/client/node_modules
      - ./client:/app/client