version: "3.9"  # optional since v1.27.0
services:
  ck-frontend:
    build: 
      dockerfile: Dockerfile
      context: ./client
    container_name: ck-react
    command: npm start /client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client