version: '3.9'

services:
    web:
      build: .
      container_name: ck-django
      command: python /app/my_django_site/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app
      ports:
        - "8000:8000"

      # UNCOMMENT WHEN DEVELOPING A DOCKER APPLICATION
      # environment:
      #   - POSTGRES_NAME=postgres
      #   - POSTGRES_USER=postgres
      #   - POSTGRES_PASSWORD=postgres
      # depends_on:
      #   - db